name: 01 - Pipeline
on: push

jobs:
  jobs:
    echo-hello:
      runs-on: ubuntu-latest
      steps:
        - name: Start
          run: echo "Hello world"
    
    echo-goodby:
      runs-on: ubuntu-latest
      steps:
        - name: Failed step
	  run: |
            echo "This step will fail"
            exit 1
        - name: goodbye
          run: echo "Goodbye!"

      
