name: 03 Workflow Runners
on: push

jobs:
  ububtu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show os
        run: |
          echo "This job runs on a Ubuntu runner"
          echo "Runner OS: $RUNNER_OS"

