name: 03 Workflow Runners
on: workflow_dispatch

jobs:
  ububtu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show os
        run: |
          echo "This job runs on a Ubuntu runner"
          echo "Runner OS: $RUNNER_OS"
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show os
        shell: bash
        run: |
          echo "This job runs on a Windows runner"
          echo "Runner OS: $RUNNER_OS"
  mac-echo:
    runs-on: macos-latest
    steps:
      - name: Show os
        run: |
          echo "This job runs on a Mac runner"
          echo "Runner OS: $RUNNER_OS"

