name: 01 - Pipeline
on: workflow_dispatch

jobs:
    echo-hello:
      runs-on: ubuntu-latest
      steps:
        - name: Start
          run: echo "Hello world"
    
    echo-goodbye:
      runs-on: ubuntu-latest
      steps:
        - name: Succ step
          run: |
            echo "This step will succeed"
            exit 0
        - name: goodbye
          run: echo "Goodbye!"
